# Bash specifics
stty start undef
stty stop undef
export HISTSIZE=5000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth:erasedups # no duplicate entries
shopt -s histappend                     # append history file
export PROMPT_COMMAND="history -a"      # update histfile after every command


# Use mkshrc for most config
source $HOME/.mkshrc

# Ruby helpers
if [ -n "$BASH_VERSION" ] || [ -n "$ZSH_VERSION" ]; then
  if [ -d /usr/local/share/chruby ]; then
    source /usr/local/share/chruby/chruby.sh
    source /usr/local/share/chruby/auto.sh
  fi
fi

# Status line
export PS1="\[\e[0;36m\]\W>\[\e[0m\] "
