" Don't bother supporting vi, update window title, no ~file
set nocompatible title nobackup noswapfile
" Show line number, current line and current command
set number cursorline showcmd
" Search incrementally with smart case sensitivity, highlight all matches
set incsearch ignorecase smartcase hlsearch
" Automatic indentation and adjust with tab and backspace
set autoindent smartindent smarttab
" Shorten messages, disable intro screen and disable audible bell
set shortmess=atI visualbell t_vb=
" Allow backspace in insert mode, show hard tabs and trailing whitespace
set backspace=2 list listchars=tab:>\ ,trail:·,nbsp:_
" Show hard tabs as 4 wide, use 2 space indentation rounded to multiples
set tabstop=4 expandtab shiftwidth=2 shiftround
" Show tab-complete suggestions and complete longest substring.
set wildmenu wildmode=list:longest
" Color line 100
set colorcolumn=100
" Fold on { { {
set foldmethod=marker foldlevelstart=10
" Use space as leader
let mapleader=" "
" Use os's clipboard
if (executable('pbcopy') || executable('xclip') || executable('xsel')) && has('clipboard')
  set clipboard=unnamed
endif
" Use zsh
set shell=zsh

" Packages
call plug#begin()
" Plugins
Plug 'neomake/neomake'
Plug 'nvie/vim-flake8'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-vinegar'
Plug 'ervandew/supertab'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'jlanzarotta/bufexplorer'
Plug 'editorconfig/editorconfig-vim'

" Languages
Plug 'mxw/vim-jsx'
Plug 'fatih/vim-go'
Plug 'klen/python-mode'
Plug 'pangloss/vim-javascript'
call plug#end()

" Syntax highlighting, filetype indentation rules, color scheme
syntax on
filetype plugin indent on
set background=light
colorscheme solarized " dracula smyck delek bwop

" Status line
hi statusline ctermfg=0 ctermbg=5
hi statuslinenc ctermfg=0 ctermbg=6
set statusline=\ %f\ %m\ %r%=(%c,\ %l)\ -\ %l\ 

" Auto commands
autocmd VimResized * :wincmd = " Equalize window sizes on resize
autocmd BufNewFile,BufRead *.md setlocal spell " Help correct my english

" Map Ctrl+[hjkl] to move around splits
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
nnoremap <C-w>n <ESC>:tabnext<CR>
if has("nvim")
  nmap <BS> <C-W>h " Hack to get C-h working in neovim
  tnoremap <Esc> <C-\><C-n>
end

" Leader commands
nmap <leader>n :nohlsearch<CR>
noremap <leader>b :BufExplorer<CR>
noremap <leader>f :execute 'edit %:h/'<CR>
noremap <leader>t :CtrlP<CR>
cmap w!! w !sudo tee % > /dev/null

augroup vinergar_custom
  autocmd!
  autocmd FileType netrw nnoremap <buffer> <silent> <Esc> :bdelete<CR>
augroup END

" CtrlP
let g:ctrlp_root_markers = ['node_modules']
let g:ctrlp_custom_ignore = { 'dir':  '\.git$\|node_modules', 'file': '\.exe$\|\.so$\|\.DS_Store|.*\.pyc', }

" Neomake
autocmd BufWritePost * Neomake
hi NeomakeErrorSign ctermfg=black ctermbg=red
hi NeomakeWarningSign ctermfg=black ctermbg=yellow
let g:neomake_javascript_enabled_makers = ['eslint']

" Ag
set grepprg=ag\ --vimgrep\ $*
set grepformat=%f:%l:%c:%m

" Go
let g:go_fmt_command = "goimports"
let g:go_list_type = "quickfix"

" Rust
let g:rustfmt_autosave = 1
