set nobackup noswapfile
set scrolloff=1 colorcolumn=80,100 list listchars=tab:»\ ,trail:·
set splitbelow splitright statusline=\ %f\ %y\ %m\ %r%=(%c,\ %l)\ 
set number ruler cursorline shortmess=atI foldmethod=marker foldlevelstart=10
set lisp autoindent cindent expandtab tabstop=2 shiftwidth=2 wildmode=list:longest
set timeout timeoutlen=1000 ttimeoutlen=100
syntax on
colorscheme u
let mapleader=" "
nmap <leader><leader> :nohlsearch<CR>
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
vmap <C-c> :!xclip -f -sel clip<CR>
autocmd VimResized * :wincmd =
autocmd BufWinEnter *.tmpl set filetype=html

call plug#begin()
Plug 'w0rp/ale'
Plug 'tpope/vim-vinegar'
Plug 'kien/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }
Plug 'b4b4r07/vim-hcl'
Plug 'plasticboy/vim-markdown'
Plug 'leafgarland/typescript-vim'
call plug#end()

let g:go_fmt_command = 'goimports'
let g:go_list_type = 'quickfix'
let g:ale_fix_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_fixers = {'javascript': ['prettier']}
let g:ale_linters = {'javascript': ['eslint'],'go': ['gofmt', 'golint', 'go vet', 'go build']}
let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let g:ctrlp_match_window = 'bottom,order:btt,min:5,max:5,results:10'
let g:ctrlp_cmd = 'CtrlPMixed'
let g:ctrlp_mruf_default_order = 1
