xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

setxkbmap -option ctrl:swapcaps # Swap Left Control and Caps Lock
setxkbmap -option ctrl:nocaps   # Make left ctrl a ctrl not caps
