#!/usr/bin/fish

sudo apt-get install curl git

set -l code $HOME/code

for directory in $code "$HOME/.bin" "$code/dev" "$code/repos" "$code/libs"
  if not test -d $directory
    (mkdir $directory)
  end
end
if test -f "$HOME/.env"
  (touch $HOME/.env)
end

# Setup shell
if not test -f ~/.config/fish/config.fish
  (mkdir -p ~/.config/fish/functions/)
  (ln -s ~/dotfiles/config.fish ~/.config/fish/config.fish)
  (ln -s ~/dotfiles/fish_prompt.fish ~/.config/fish/functions/fish_prompt.fish)
end

# Install composer
rm "$HOME/.bin/composer"
cd "$code/dev"
curl -sS https://getcomposer.org/installer | php
ln -s $code/dev/composer.phar $HOME/.bin/composer

# Setup dotfiles
touch ~/.hushlogin
ln -s ~/dotfiles/gitconfig ~/.gitconfig
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/vimrc ~/.vimrc
ln -s ~/dotfiles/vim ~/.vim
